#pragma once
// STL
#include <algorithm>
#include <initializer_list>
#include <iostream>
#include <memory>
#include <span>
#include <sstream>
#include <stdexcept>
#include <utility>
// TPL
#define FMT_HEADER_ONLY
#include <fmt/format.h>